# Generated by Django 5.1.5 on 2025-01-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ingredients', models.CharField(help_text='Separate each ingredient with comma', max_length=500)),
                ('cooking_time', models.PositiveIntegerField(help_text='Cooking time in minutes')),
                ('difficulty', models.CharField(blank=True, editable=False, max_length=20, null=True)),
                ('description', models.TextField()),
                ('pic', models.ImageField(default='no_picture.jpg', upload_to='recipes')),
            ],
        ),
    ]
