# Generated by Django 5.1.5 on 2025-01-21 12:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='pic',
            field=cloudinary.models.CloudinaryField(default='no_picture.jpg', max_length=255, verbose_name='image'),
        ),
    ]
